development:
  adapter: postgresql
  encoding: utf8
  database: my_dev_db
  pool: 5
  timeout: 5000
  #username
  #password
  #host
  #port

test:
  adapter: postgresql
  encoding: utf8
  database: my_dev_db
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: utf8
  database: my_dev_db
  pool: 5
  timeout: 5000
  #username
  #password
  #host
  #port
